### ISSUE TITLE
Request Postgresql 

### ISSUE THREAD

**Issue by triadmoko** [cahyadsn/wilayah_boundaries#1]
Hallo mas. Saya sedikit kesulitan untuk insert data ke dalam  database postgres. Karna terdapat error yang sedikit susah untuk di tracking karna datanya yang begitu banyak. kedepannya apakah ada script untuk postgres ?
Terimakasih mas.

**Comment by cahyadsn** [comment]
saya masukin ke todo list dulu ya, terima kasih masukannya
